apiVersion: v1
kind: Secret
metadata:
    name: mysql
    namespace: final
data:
    DBHOST: bXlzcWwuZmluYWwuc3ZjLmNsdXN0ZXIubG9jYWw=
    DBUSER: cm9vdA==
    DBPWD: ZGJfcGFzczEyMw==
    DBPORT: MzMwNg==